In [1]:
import pandas as pd

In [133]:
data = pd.read_csv('world_development_indicators.csv')
wdi = pd.DataFrame(data)

In [3]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446 entries, 0 to 445
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    446 non-null    object
 1   access_to_electricity_pct       446 non-null    float64
 2   atms_per_100000                 417 non-null    float64
 3   compulsory_education_years      424 non-null    float64
 4   health_expenditure_pct_of_gdp   439 non-null    float64
 5   gdp_per_capita_usd              446 non-null    float64
 6   gdp_per_capita_ppp              446 non-null    float64
 7   life_expectancy_female          446 non-null    float64
 8   life_expectancy_male            446 non-null    float64
 9   life_expectancy                 446 non-null    float64
 10  population_density              444 non-null    float64
 11  population                      446 non-null    float64
 12  alcohol_consumption_per_capita  220 non-null    float64
 13  unemployment_rate_female        446 non-null    float64
 14  unemployment_rate_male          446 non-null    float64
 15  unemployment_rate               446 non-null    float64
 16  year                            446 non-null    int64
 17  Country Name                    446 non-null    object
 18  Country Code                    446 non-null    object
 19  country_category                289 non-null    object
 20  is_region                       446 non-null    int64
 21  planet                          446 non-null    object
dtypes: float64(15), int64(2), object(5)
memory usage: 76.8+ KB

In [5]:
wdi[['country_name', 'Country Name', 'Country Code', 'planet']]

             country_name          Country Name Country Code planet
0             Afghanistan           Afghanistan          AFG  Earth
1                 Albania               Albania          ALB  Earth
2                 Algeria               Algeria          DZA  Earth
3                  Angola                Angola          AGO  Earth
4              Arab World            Arab World          ARB  Earth
..                    ...                   ...          ...    ...
441               Ukraine               Ukraine          UKR  Earth
442           Philippines           Philippines          PHL  Earth
443             Indonesia             Indonesia          IDN  Earth
444  United Arab Emirates  United Arab Emirates          ARE  Earth
445               Comoros               Comoros          COM  Earth

[446 rows x 4 columns]

In [6]:
wdi.nunique()

country_name                      217
access_to_electricity_pct         240
atms_per_100000                   359
compulsory_education_years         16
health_expenditure_pct_of_gdp     421
gdp_per_capita_usd                430
gdp_per_capita_ppp                430
life_expectancy_female            390
life_expectancy_male              402
life_expectancy                   425
population_density                428
population                        430
alcohol_consumption_per_capita    204
unemployment_rate_female          422
unemployment_rate_male            430
unemployment_rate                 428
year                                2
Country Name                      217
Country Code                      217
country_category                    2
is_region                           2
planet                              1
dtype: int64

In [8]:
wdi['planet'].value_counts()

planet
Earth    446
Name: count, dtype: int64

In [11]:
wdi['planet'].value_counts(normalize=True)

planet
Earth    1.0
Name: proportion, dtype: float64

In [12]:
wdi[wdi['country_name'] != wdi['Country Name']]

Empty DataFrame
Columns: [country_name, access_to_electricity_pct, atms_per_100000, compulsory_education_years, health_expenditure_pct_of_gdp, gdp_per_capita_usd, gdp_per_capita_ppp, life_expectancy_female, life_expectancy_male, life_expectancy, population_density, population, alcohol_consumption_per_capita, unemployment_rate_female, unemployment_rate_male, unemployment_rate, year, Country Name, Country Code, country_category, is_region, planet]
Index: []

[0 rows x 22 columns]

In [13]:
wdi['Country Name'].compare(wdi['Country Name'])

Empty DataFrame
Columns: [self, other]
Index: []

In [14]:
wdi['Country Name'].compare(wdi['Country Code'])

                     self other
0             Afghanistan   AFG
1                 Albania   ALB
2                 Algeria   DZA
3                  Angola   AGO
4              Arab World   ARB
..                    ...   ...
441               Ukraine   UKR
442           Philippines   PHL
443             Indonesia   IDN
444  United Arab Emirates   ARE
445               Comoros   COM

[446 rows x 2 columns]

In [18]:
wdi[['Country Name', 'Country Code']].value_counts()

Country Name        Country Code
Belarus             BLR             3
Euro area           EMU             3
Comoros             COM             3
Tajikistan          TJK             3
Timor-Leste         TLS             3
                                   ..
Vietnam             VNM             2
West Bank and Gaza  PSE             2
World               WLD             2
Zambia              ZMB             2
Zimbabwe            ZWE             2
Name: count, Length: 217, dtype: int64

In [19]:
wdi.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
441     True
442     True
443     True
444     True
445     True
Length: 446, dtype: bool

In [22]:
print(wdi.shape)
wdi = wdi.drop_duplicates(ignore_index=True)

(446, 22)

In [23]:
wdi.shape

(434, 22)

In [25]:
wdi.describe()

,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,is_region
count,434.000000,406.000000,412.000000,427.000000,434.000000,434.000000,434.000000,434.000000,434.000000,432.000000,4.340000e+02,215.000000,434.000000,434.000000,434.000000,434.000000,434.000000
mean,84.215517,48.128568,9.701456,6.433350,13599.891623,19925.226075,74.569474,69.866522,72.176272,209.973753,3.690135e+08,6.016516,8.404762,6.465617,7.047682,2017.500000,0.211982
std,24.389620,43.078263,2.206372,2.622327,18647.562977,19970.698889,7.676443,7.144252,7.334379,747.286538,1.049035e+09,3.783835,6.863858,4.535745,5.026820,0.500577,0.409184
min,9.300000,1.213235,5.000000,2.138482,271.752044,773.571858,54.354000,49.837000,52.240000,2.004286,1.019980e+05,0.003000,0.369000,0.052000,0.110000,2017.000000,0.000000
25%,70.842500,14.305347,9.000000,4.493300,1971.836316,4989.813770,69.050750,65.297750,66.988750,35.045644,4.312760e+06,2.720000,3.893250,3.796250,3.946283,2017.000000,0.000000
50%,98.912941,39.411075,10.000000,6.006967,5783.711368,13108.453526,76.088500,70.813500,73.585501,69.610676,1.604842e+07,5.837431,5.836087,5.351708,5.606500,2017.500000,0.000000
75%,100.000000,65.059316,11.000000,7.960797,15561.550814,28646.342748,80.144500,74.659500,77.162500,133.921155,1.026882e+08,9.095000,10.286000,8.001815,9.051000,2018.000000,0.000000
max,100.000000,272.592801,16.000000,17.003614,116654.261067,116786.479974,87.700000,82.300000,84.934146,7952.998418,7.591945e+09,15.090000,42.769001,25.238001,27.070999,2018.000000,1.000000

In [26]:
wdi.describe().T

,count,mean,std,min,25%,50%,75%,max
access_to_electricity_pct,434.0,8.421552e+01,2.438962e+01,9.300000,7.084250e+01,9.891294e+01,1.000000e+02,1.000000e+02
atms_per_100000,406.0,4.812857e+01,4.307826e+01,1.213235,1.430535e+01,3.941107e+01,6.505932e+01,2.725928e+02
compulsory_education_years,412.0,9.701456e+00,2.206372e+00,5.000000,9.000000e+00,1.000000e+01,1.100000e+01,1.600000e+01
health_expenditure_pct_of_gdp,427.0,6.433350e+00,2.622327e+00,2.138482,4.493300e+00,6.006967e+00,7.960797e+00,1.700361e+01
gdp_per_capita_usd,434.0,1.359989e+04,1.864756e+04,271.752044,1.971836e+03,5.783711e+03,1.556155e+04,1.166543e+05
gdp_per_capita_ppp,434.0,1.992523e+04,1.997070e+04,773.571858,4.989814e+03,1.310845e+04,2.864634e+04,1.167865e+05
life_expectancy_female,434.0,7.456947e+01,7.676443e+00,54.354000,6.905075e+01,7.608850e+01,8.014450e+01,8.770000e+01
life_expectancy_male,434.0,6.986652e+01,7.144252e+00,49.837000,6.529775e+01,7.081350e+01,7.465950e+01,8.230000e+01
life_expectancy,434.0,7.217627e+01,7.334379e+00,52.240000,6.698875e+01,7.358550e+01,7.716250e+01,8.493415e+01
population_density,432.0,2.099738e+02,7.472865e+02,2.004286,3.504564e+01,6.961068e+01,1.339212e+02,7.952998e+03
population,434.0,3.690135e+08,1.049035e+09,101998.000000,4.312760e+06,1.604842e+07,1.026882e+08,7.591945e+09
alcohol_consumption_per_capita,215.0,6.016516e+00,3.783835e+00,0.003000,2.720000e+00,5.837431e+00,9.095000e+00,1.509000e+01
unemployment_rate_female,434.0,8.404762e+00,6.863858e+00,0.369000,3.893250e+00,5.836087e+00,1.028600e+01,4.276900e+01
unemployment_rate_male,434.0,6.465617e+00,4.535745e+00,0.052000,3.796250e+00,5.351708e+00,8.001815e+00,2.523800e+01
unemployment_rate,434.0,7.047682e+00,5.026820e+00,0.110000,3.946283e+00,5.606500e+00,9.051000e+00,2.707100e+01
year,434.0,2.017500e+03,5.005770e-01,2017.000000,2.017000e+03,2.017500e+03,2.018000e+03,2.018000e+03
is_region,434.0,2.119816e-01,4.091835e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00

In [30]:
wdi.isna()
wdi.isnull()

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,...,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,Country Name,Country Code,country_category,is_region,planet
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
430,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
431,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
432,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
433,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [32]:
wdi.notna()
wdi.notnull()

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,...,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,Country Name,Country Code,country_category,is_region,planet
0,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
430,True,True,True,True,False,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
431,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,False,True,True
432,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
433,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [33]:
wdi.isna().sum()

country_name                        0
access_to_electricity_pct           0
atms_per_100000                    28
compulsory_education_years         22
health_expenditure_pct_of_gdp       7
gdp_per_capita_usd                  0
gdp_per_capita_ppp                  0
life_expectancy_female              0
life_expectancy_male                0
life_expectancy                     0
population_density                  2
population                          0
alcohol_consumption_per_capita    219
unemployment_rate_female            0
unemployment_rate_male              0
unemployment_rate                   0
year                                0
Country Name                        0
Country Code                        0
country_category                  152
is_region                           0
planet                              0
dtype: int64

In [35]:
wdi.isna().sum(axis=1)

0      1
1      1
2      1
3      1
4      2
      ..
429    0
430    2
431    1
432    0
433    0
Length: 434, dtype: int64

In [36]:
num_missing_row = wdi.isna().sum(axis=1)

In [38]:
wdi[num_missing_row>0]

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,...,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,Country Name,Country Code,country_category,is_region,planet
0,Afghanistan,97.700000,1.213235,9.0,11.777236,519.884773,2058.383832,65.656000,62.701000,64.130000,...,NaN,14.090000,10.416000,11.184000,2017,Afghanistan,AFG,DEVELOPING,0,Earth
1,Albania,100.000000,31.714076,9.0,5.010597,4531.020806,13037.010016,80.148000,76.601000,78.333000,...,NaN,12.563000,14.590000,13.750000,2017,Albania,ALB,DEVELOPING,0,Earth
2,Algeria,100.000000,9.130677,10.0,6.380329,4111.294110,11737.409353,77.735000,75.307000,76.499000,...,NaN,21.114000,10.021000,11.996000,2017,Algeria,DZA,DEVELOPING,0,Earth
3,Angola,41.962894,19.079250,6.0,2.791503,4095.812942,7310.901738,63.252000,57.677000,60.379000,...,NaN,7.467000,6.769000,7.119000,2017,Angola,AGO,DEVELOPING,0,Earth
4,Arab World,90.283638,27.360620,9.0,5.561266,6108.588220,14562.367966,73.493366,69.921250,71.622526,...,NaN,20.361396,8.097088,10.641313,2017,Arab World,ARB,NaN,1,Earth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,Upper middle income,99.423212,54.376093,10.0,5.739787,8906.243876,16701.291315,78.040738,72.790446,75.328985,...,6.170874,5.809633,5.812897,5.811807,2018,Upper middle income,UMC,NaN,1,Earth
426,Uruguay,100.000000,120.067132,14.0,9.202700,17277.970111,22116.786596,81.359000,73.958000,77.770000,...,6.920000,10.089000,6.873000,8.336000,2018,Uruguay,URY,NaN,0,Earth
428,Vanuatu,61.864769,48.050330,NaN,3.373726,3125.257989,3204.679541,71.990000,68.847000,70.323000,...,2.250000,4.898000,3.958000,4.368000,2018,Vanuatu,VUT,DEVELOPING,0,Earth
430,West Bank and Gaza,100.000000,24.735190,10.0,NaN,3562.330943,6472.121785,75.595000,72.263000,73.895000,...,NaN,41.849998,22.393999,26.256001,2018,West Bank and Gaza,PSE,DEVELOPING,0,Earth
431,World,89.588551,40.949620,10.0,9.848779,11385.675227,17025.827360,74.871815,70.398743,72.563282,...,6.181240,5.580954,5.271615,5.392213,2018,World,WLD,NaN,1,Earth

In [40]:
wdi.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 115 entries, 217 to 433
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    115 non-null    object
 1   access_to_electricity_pct       115 non-null    float64
 2   atms_per_100000                 115 non-null    float64
 3   compulsory_education_years      115 non-null    float64
 4   health_expenditure_pct_of_gdp   115 non-null    float64
 5   gdp_per_capita_usd              115 non-null    float64
 6   gdp_per_capita_ppp              115 non-null    float64
 7   life_expectancy_female          115 non-null    float64
 8   life_expectancy_male            115 non-null    float64
 9   life_expectancy                 115 non-null    float64
 10  population_density              115 non-null    float64
 11  population                      115 non-null    float64
 12  alcohol_consumption_per_capita  115 non-null    float64
 13  unemployment_rate_female        115 non-null    float64
 14  unemployment_rate_male          115 non-null    float64
 15  unemployment_rate               115 non-null    float64
 16  year                            115 non-null    int64
 17  Country Name                    115 non-null    object
 18  Country Code                    115 non-null    object
 19  country_category                115 non-null    object
 20  is_region                       115 non-null    int64
 21  planet                          115 non-null    object
dtypes: float64(15), int64(2), object(5)
memory usage: 20.7+ KB

In [42]:
wdi.dropna().nunique()

country_name                      115
access_to_electricity_pct          56
atms_per_100000                   115
compulsory_education_years         12
health_expenditure_pct_of_gdp     115
gdp_per_capita_usd                115
gdp_per_capita_ppp                115
life_expectancy_female            107
life_expectancy_male              110
life_expectancy                   115
population_density                115
population                        115
alcohol_consumption_per_capita    112
unemployment_rate_female          114
unemployment_rate_male            114
unemployment_rate                 115
year                                1
Country Name                      115
Country Code                      115
country_category                    2
is_region                           1
planet                              1
dtype: int64

In [44]:
wdi.dropna(axis=1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   country_name               434 non-null    object
 1   access_to_electricity_pct  434 non-null    float64
 2   gdp_per_capita_usd         434 non-null    float64
 3   gdp_per_capita_ppp         434 non-null    float64
 4   life_expectancy_female     434 non-null    float64
 5   life_expectancy_male       434 non-null    float64
 6   life_expectancy            434 non-null    float64
 7   population                 434 non-null    float64
 8   unemployment_rate_female   434 non-null    float64
 9   unemployment_rate_male     434 non-null    float64
 10  unemployment_rate          434 non-null    float64
 11  year                       434 non-null    int64
 12  Country Name               434 non-null    object
 13  Country Code               434 non-null    object
 14  is_region                  434 non-null    int64
 15  planet                     434 non-null    object
dtypes: float64(10), int64(2), object(4)
memory usage: 54.4+ KB

In [48]:
wdi.dropna(thresh=300, axis=1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   country_name                   434 non-null    object
 1   access_to_electricity_pct      434 non-null    float64
 2   atms_per_100000                406 non-null    float64
 3   compulsory_education_years     412 non-null    float64
 4   health_expenditure_pct_of_gdp  427 non-null    float64
 5   gdp_per_capita_usd             434 non-null    float64
 6   gdp_per_capita_ppp             434 non-null    float64
 7   life_expectancy_female         434 non-null    float64
 8   life_expectancy_male           434 non-null    float64
 9   life_expectancy                434 non-null    float64
 10  population_density             432 non-null    float64
 11  population                     434 non-null    float64
 12  unemployment_rate_female       434 non-null    float64
 13  unemployment_rate_male         434 non-null    float64
 14  unemployment_rate              434 non-null    float64
 15  year                           434 non-null    int64
 16  Country Name                   434 non-null    object
 17  Country Code                   434 non-null    object
 18  is_region                      434 non-null    int64
 19  planet                         434 non-null    object
dtypes: float64(14), int64(2), object(4)
memory usage: 67.9+ KB

In [46]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    434 non-null    object
 1   access_to_electricity_pct       434 non-null    float64
 2   atms_per_100000                 406 non-null    float64
 3   compulsory_education_years      412 non-null    float64
 4   health_expenditure_pct_of_gdp   427 non-null    float64
 5   gdp_per_capita_usd              434 non-null    float64
 6   gdp_per_capita_ppp              434 non-null    float64
 7   life_expectancy_female          434 non-null    float64
 8   life_expectancy_male            434 non-null    float64
 9   life_expectancy                 434 non-null    float64
 10  population_density              432 non-null    float64
 11  population                      434 non-null    float64
 12  alcohol_consumption_per_capita  215 non-null    float64
 13  unemployment_rate_female        434 non-null    float64
 14  unemployment_rate_male          434 non-null    float64
 15  unemployment_rate               434 non-null    float64
 16  year                            434 non-null    int64
 17  Country Name                    434 non-null    object
 18  Country Code                    434 non-null    object
 19  country_category                282 non-null    object
 20  is_region                       434 non-null    int64
 21  planet                          434 non-null    object
dtypes: float64(15), int64(2), object(5)
memory usage: 74.7+ KB

In [56]:
num_cols = wdi.select_dtypes(include=['number']).columns
cat_cols = wdi.select_dtypes(exclude=['number']).columns

In [57]:
wdi[num_cols] = wdi[num_cols].fillna(wdi[num_cols].mean())

C:\Users\Aniruddha\AppData\Local\Temp\ipykernel_16832\1092961224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wdi[num_cols] = wdi[num_cols].fillna(wdi[num_cols].mean())

In [59]:
wdi.isnull().sum()

country_name                        0
access_to_electricity_pct           0
atms_per_100000                     0
compulsory_education_years          0
health_expenditure_pct_of_gdp       0
gdp_per_capita_usd                  0
gdp_per_capita_ppp                  0
life_expectancy_female              0
life_expectancy_male                0
life_expectancy                     0
population_density                  0
population                          0
alcohol_consumption_per_capita      0
unemployment_rate_female            0
unemployment_rate_male              0
unemployment_rate                   0
year                                0
Country Name                        0
Country Code                        0
country_category                  152
is_region                           0
planet                              0
dtype: int64

In [62]:
wdi['alcohol_consumption_per_capita'].value_counts(dropna=False)

alcohol_consumption_per_capita
6.016516     219
0.690000       3
11.450000      2
0.019000       2
0.430000       2
            ...
2.250000       1
8.660000       1
6.181240       1
6.540000       1
4.670000       1
Name: count, Length: 205, dtype: int64

In [65]:
wdi['country_category'].value_counts(dropna=False)

country_category
DEVELOPING    224
NaN           152
DEVELOPED      58
Name: count, dtype: int64

In [67]:
from sklearn.impute import SimpleImputer
simple_imp_num=SimpleImputer(strategy='constant', fill_value=-999)

In [72]:
imputed_num = simple_imp_num.fit_transform(wdi[num_cols])

In [73]:
wdi[num_cols] = imputed_num

C:\Users\Aniruddha\AppData\Local\Temp\ipykernel_16832\2544374347.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wdi[num_cols] = imputed_num

In [87]:
simple_imp_cat=SimpleImputer(strategy='most_frequent')

In [88]:
imputed_cat = simple_imp_cat.fit_transform(wdi[['country_category']])

In [89]:
print(imputed_cat)

[['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPED']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPED']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPED']
 ['Missing']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPED']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPED']
 ['DEVELOPED']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPED']
 ['DEVELOPED']
 ['Missing']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['DEVELOPING']
 ['Missing']
 ['DEVELOPING']
 ['DEVELOPING']]

In [90]:
wdi['country_category'] = imputed_cat.flatten()

C:\Users\Aniruddha\AppData\Local\Temp\ipykernel_16832\155966949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wdi['country_category'] = imputed_cat.flatten()

In [91]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    434 non-null    object
 1   access_to_electricity_pct       434 non-null    float64
 2   atms_per_100000                 434 non-null    float64
 3   compulsory_education_years      434 non-null    float64
 4   health_expenditure_pct_of_gdp   434 non-null    float64
 5   gdp_per_capita_usd              434 non-null    float64
 6   gdp_per_capita_ppp              434 non-null    float64
 7   life_expectancy_female          434 non-null    float64
 8   life_expectancy_male            434 non-null    float64
 9   life_expectancy                 434 non-null    float64
 10  population_density              434 non-null    float64
 11  population                      434 non-null    float64
 12  alcohol_consumption_per_capita  434 non-null    float64
 13  unemployment_rate_female        434 non-null    float64
 14  unemployment_rate_male          434 non-null    float64
 15  unemployment_rate               434 non-null    float64
 16  year                            434 non-null    float64
 17  Country Name                    434 non-null    object
 18  Country Code                    434 non-null    object
 19  country_category                434 non-null    object
 20  is_region                       434 non-null    float64
 21  planet                          434 non-null    object
dtypes: float64(17), object(5)
memory usage: 74.7+ KB

In [93]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446 entries, 0 to 445
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    446 non-null    object
 1   access_to_electricity_pct       446 non-null    float64
 2   atms_per_100000                 417 non-null    float64
 3   compulsory_education_years      424 non-null    float64
 4   health_expenditure_pct_of_gdp   439 non-null    float64
 5   gdp_per_capita_usd              446 non-null    float64
 6   gdp_per_capita_ppp              446 non-null    float64
 7   life_expectancy_female          446 non-null    float64
 8   life_expectancy_male            446 non-null    float64
 9   life_expectancy                 446 non-null    float64
 10  population_density              444 non-null    float64
 11  population                      446 non-null    float64
 12  alcohol_consumption_per_capita  220 non-null    float64
 13  unemployment_rate_female        446 non-null    float64
 14  unemployment_rate_male          446 non-null    float64
 15  unemployment_rate               446 non-null    float64
 16  year                            446 non-null    int64
 17  Country Name                    446 non-null    object
 18  Country Code                    446 non-null    object
 19  country_category                289 non-null    object
 20  is_region                       446 non-null    int64
 21  planet                          446 non-null    object
dtypes: float64(15), int64(2), object(5)
memory usage: 76.8+ KB

In [102]:
type(cat_cols)

pandas.core.indexes.base.Index

In [114]:
most_freq = wdi[cat_cols].describe().loc['top']

In [116]:
wdi[cat_cols] = wdi[cat_cols].fillna(most_freq)

In [123]:
wdi['country_category'].value_counts()

country_category
DEVELOPING    388
DEVELOPED      58
Name: count, dtype: int64

In [124]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446 entries, 0 to 445
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    446 non-null    object
 1   access_to_electricity_pct       446 non-null    float64
 2   atms_per_100000                 417 non-null    float64
 3   compulsory_education_years      424 non-null    float64
 4   health_expenditure_pct_of_gdp   439 non-null    float64
 5   gdp_per_capita_usd              446 non-null    float64
 6   gdp_per_capita_ppp              446 non-null    float64
 7   life_expectancy_female          446 non-null    float64
 8   life_expectancy_male            446 non-null    float64
 9   life_expectancy                 446 non-null    float64
 10  population_density              444 non-null    float64
 11  population                      446 non-null    float64
 12  alcohol_consumption_per_capita  220 non-null    float64
 13  unemployment_rate_female        446 non-null    float64
 14  unemployment_rate_male          446 non-null    float64
 15  unemployment_rate               446 non-null    float64
 16  year                            446 non-null    int64
 17  country_category                446 non-null    object
 18  is_region                       446 non-null    int64
dtypes: float64(15), int64(2), object(2)
memory usage: 66.3+ KB

In [134]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [135]:
iter_imp = IterativeImputer(min_value=wdi[num_cols].min(), max_value=wdi[num_cols].max())

In [136]:
imputed_data = iter_imp.fit_transform(wdi[num_cols])

In [137]:
wdi[num_cols] = imputed_data

In [138]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446 entries, 0 to 445
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    446 non-null    object
 1   access_to_electricity_pct       446 non-null    float64
 2   atms_per_100000                 446 non-null    float64
 3   compulsory_education_years      446 non-null    float64
 4   health_expenditure_pct_of_gdp   446 non-null    float64
 5   gdp_per_capita_usd              446 non-null    float64
 6   gdp_per_capita_ppp              446 non-null    float64
 7   life_expectancy_female          446 non-null    float64
 8   life_expectancy_male            446 non-null    float64
 9   life_expectancy                 446 non-null    float64
 10  population_density              446 non-null    float64
 11  population                      446 non-null    float64
 12  alcohol_consumption_per_capita  446 non-null    float64
 13  unemployment_rate_female        446 non-null    float64
 14  unemployment_rate_male          446 non-null    float64
 15  unemployment_rate               446 non-null    float64
 16  year                            446 non-null    float64
 17  Country Name                    446 non-null    object
 18  Country Code                    446 non-null    object
 19  country_category                289 non-null    object
 20  is_region                       446 non-null    float64
 21  planet                          446 non-null    object
dtypes: float64(17), object(5)
memory usage: 76.8+ KB