In [1]:
import pandas as pd
data = pd.read_csv('marvel_characters_dataset.csv')
df = pd.DataFrame(data)

In [2]:
df.head()

,Character,Real Name,Affiliation,Powers,Role,Power Level
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Hero,Low
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Hero,Low
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Hero,Low
3,black widow,Natasha Romanoff,Avengers,"Superhuman strength, Espionage",Hero,Low
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Hero,Low

In [3]:
df['Role'] = df['Role'] + 'str'

In [5]:
df.loc[2, 'Role'] = 'Aniruddha'

In [6]:
df.head()

,Character,Real Name,Affiliation,Powers,Role,Power Level
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low
3,black widow,Natasha Romanoff,Avengers,"Superhuman strength, Espionage",Herostr,Low
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low

In [7]:
df.iloc[3,2:4] = 'doreamon'

In [9]:
df.head()

,Character,Real Name,Affiliation,Powers,Role,Power Level
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low
3,black widow,Natasha Romanoff,doreamon,doreamon,Herostr,Low
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low

In [12]:
df['Age'] = range(df.shape[0])

In [20]:
df.head()

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low,20
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low,21
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low,22
3,black widow,Natasha Romanoff,doreamon,doreamon,Herostr,Low,23
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low,24

In [21]:
df['Age'] = df['Age']+15

In [22]:
df.head()

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low,35
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low,36
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low,37
3,black widow,Natasha Romanoff,doreamon,doreamon,Herostr,Low,38
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low,39

In [23]:
df['Character'] = df['Character'].apply(str.upper)

In [25]:
df.head()

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
0,IRON MAN,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low,35
1,CAPTAIN AMERICA,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low,36
2,THOR,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low,37
3,BLACK WIDOW,Natasha Romanoff,doreamon,doreamon,Herostr,Low,38
4,HULK,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low,39

In [26]:
df['Character'] = df['Character'].map({'IRON MAN':"Nobita", 'THOR':'Giyan'})

In [27]:
df.head()

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
0,Nobita,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low,35
1,NaN,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low,36
2,Giyan,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low,37
3,NaN,Natasha Romanoff,doreamon,doreamon,Herostr,Low,38
4,NaN,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low,39

In [28]:
df['Age'] = df['Age'].mask(df['Age']>36, 0)

In [29]:
df.head()

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
0,Nobita,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low,35
1,NaN,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low,36
2,Giyan,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low,0
3,NaN,Natasha Romanoff,doreamon,doreamon,Herostr,Low,0
4,NaN,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low,0

In [30]:
df_ref = df
df_copy = df.copy()

In [31]:
print('sorting the data')

sorting the data

In [33]:
df.sort_values(by='Real Name').head()

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
37,NaN,Ben Grimm,Fantastic Four,"Invisibility, Force field generation",Herostr,Low,0
31,NaN,Blackagar Boltagon,Avengers,"Illusion creation, Hypnosis",Herostr,Low,0
4,NaN,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low,0
30,NaN,Brunnhilde,Defenders,"Superhuman intelligence, Tentacle control",Herostr,Low,0
14,NaN,Carl Lucas,Defenders,"Superhuman strength, Bulletproof skin",Herostr,Low,0

In [36]:
df.sort_values(by='Real Name', ascending=False).head()

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
11,NaN,Wanda Maximoff,Avengers,"Telekinesis, Reality warping",Herostr,Low,0
7,NaN,Wade Wilson,X-Force,"Regeneration, Skilled hand-to-hand combatant",Antiherostr,Low,0
20,NaN,Victor Von Doom,Villain,"Superhuman strength, Regeneration",Villainstr,Low,0
12,NaN,Victor Von Doom,Avengers,"Genius intellect, Magic",Herostr,Low,0
8,NaN,T’Challa,Avengers,"Superhuman strength, Vibranium suit",Herostr,Low,0

In [39]:
df[['Real Name', 'Affiliation']].sort_values(by=['Real Name', 'Affiliation']).head()

             Real Name     Affiliation
37           Ben Grimm  Fantastic Four
31  Blackagar Boltagon        Avengers
4         Bruce Banner        Avengers
30          Brunnhilde       Defenders
14          Carl Lucas       Defenders

In [40]:
df[['Real Name', 'Affiliation']].sort_values(by=['Real Name', 'Affiliation'], ascending=[True, False]).head()

             Real Name     Affiliation
37           Ben Grimm  Fantastic Four
31  Blackagar Boltagon        Avengers
4         Bruce Banner        Avengers
30          Brunnhilde       Defenders
14          Carl Lucas       Defenders

In [42]:
df.nlargest(n=10, columns='Age')

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
1,NaN,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low,36
0,Nobita,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low,35
2,Giyan,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low,0
3,NaN,Natasha Romanoff,doreamon,doreamon,Herostr,Low,0
4,NaN,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low,0
5,NaN,Peter Parker,Avengers,"Spider sense, Wall crawling",Herostr,Low,0
6,NaN,James Howlett,X-Men,"Regeneration, Adamantium claws",Herostr,Low,0
7,NaN,Wade Wilson,X-Force,"Regeneration, Skilled hand-to-hand combatant",Antiherostr,Low,0
8,NaN,T’Challa,Avengers,"Superhuman strength, Vibranium suit",Herostr,Low,0
9,NaN,Stephen Strange,Avengers,"Sorcery, Magic",Herostr,Low,0

In [43]:
df[df['Age']>30].nlargest(n=10, columns='Age')

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
1,NaN,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Herostr,Low,36
0,Nobita,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Herostr,Low,35

In [44]:
df.nsmallest(n=10, columns='Age')

,Character,Real Name,Affiliation,Powers,Role,Power Level,Age
2,Giyan,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Aniruddha,Low,0
3,NaN,Natasha Romanoff,doreamon,doreamon,Herostr,Low,0
4,NaN,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Herostr,Low,0
5,NaN,Peter Parker,Avengers,"Spider sense, Wall crawling",Herostr,Low,0
6,NaN,James Howlett,X-Men,"Regeneration, Adamantium claws",Herostr,Low,0
7,NaN,Wade Wilson,X-Force,"Regeneration, Skilled hand-to-hand combatant",Antiherostr,Low,0
8,NaN,T’Challa,Avengers,"Superhuman strength, Vibranium suit",Herostr,Low,0
9,NaN,Stephen Strange,Avengers,"Sorcery, Magic",Herostr,Low,0
10,NaN,Scott Lang,Avengers,"Size manipulation, Ant communication",Herostr,Low,0
11,NaN,Wanda Maximoff,Avengers,"Telekinesis, Reality warping",Herostr,Low,0

In [45]:
df.nsmallest(n=10, columns='Real Name')

TypeError: Column 'Real Name' has dtype object, cannot use method 'nsmallest' with this dtype