In [1]:
import pandas as pd

In [6]:
data = pd.read_csv('student.csv')
student = pd.DataFrame(data)

In [8]:
student.columns

Index(['sex', 'internet', 'studytime', 'familysize', 'age', 'score'], dtype='str')

In [9]:
student.head()

  sex internet        studytime familysize  age  score
0   F       no   2. 2 - 5 hours         >3   18      6
1   F      yes   2. 2 - 5 hours         >3   17      6
2   F      yes   2. 2 - 5 hours        <=3   15     10
3   F      yes  3. 5 - 10 hours         >3   15     15
4   F       no   2. 2 - 5 hours         >3   16     10

In [12]:
pd.pivot_table(student,
              index='sex',
              values='score')

         score
sex
F     9.966346
M    10.914439

In [17]:
pd.pivot_table(student,
              index=['sex', 'internet'],
              values=['score', 'age'],
              aggfunc=['min', 'mean', 'max'])

             min             mean            max
             age score        age      score age score
sex internet
F   no        15     0  17.078947   9.184211  19    18
    yes       15     0  16.652941  10.141176  20    19
M   no        15     0  16.928571   9.714286  21    18
    yes       15     0  16.610063  11.125786  22    20

In [19]:
pd.pivot_table(student,
              index=['sex', 'internet'],
              values='score',
              aggfunc='mean',
              columns='studytime')

studytime     1. <2 hours  2. 2 - 5 hours  3. 5 - 10 hours  4. >10 hours
sex internet
F   no           9.857143        8.909091         8.600000     10.250000
    yes          9.850000        9.637363        10.956522     11.230769
M   no           9.666667        9.600000        12.000000           NaN
    yes         10.196970       11.385714        14.000000     11.700000

In [22]:
pd.pivot_table(student,
              index=['sex', 'internet'],
              values=['score', 'age'],
              aggfunc='mean',
              columns='studytime',
              fill_value=-999)

                     age                                              \
studytime    1. <2 hours 2. 2 - 5 hours 3. 5 - 10 hours 4. >10 hours
sex internet
F   no         16.428571      17.181818       17.600000    17.000000
    yes        16.200000      16.626374       16.891304    16.692308
M   no         17.166667      16.666667       18.000000  -999.000000
    yes        16.712121      16.657143       16.692308    15.500000

                   score
studytime    1. <2 hours 2. 2 - 5 hours 3. 5 - 10 hours 4. >10 hours
sex internet
F   no          9.857143       8.909091        8.600000    10.250000
    yes         9.850000       9.637363       10.956522    11.230769
M   no          9.666667       9.600000       12.000000  -999.000000
    yes        10.196970      11.385714       14.000000    11.700000

In [24]:
pd.pivot_table(student,
              index=['sex', 'internet'],
              values=['score'],
              aggfunc='mean',
              columns=['studytime', 'internet'],
              fill_value=-999)

ValueError: Grouper for 'internet' not 1-dimensional

In [25]:
student.columns.duplicated()

array([False, False, False, False, False, False])

In [26]:
student[['sex', 'internet', 'studytime', 'score']].head()

  sex internet        studytime  score
0   F       no   2. 2 - 5 hours      6
1   F      yes   2. 2 - 5 hours      6
2   F      yes   2. 2 - 5 hours     10
3   F      yes  3. 5 - 10 hours     15
4   F       no   2. 2 - 5 hours     10

In [33]:
student.columns

Index(['sex', 'internet', 'studytime', 'familysize', 'age', 'score'], dtype='str')

In [30]:
pd.pivot_table(student,
               index='familysize',
               values='score',
               columns='sex')

sex                 F          M
familysize
<=3         10.980769  11.016129
>3           9.628205  10.864000

In [31]:
pd.pivot_table(student,
               index='familysize',
               values='score',
               columns='sex',
              margins=True,
              margins_name='Average sscore total')

sex                           F          M  Average sscore total
familysize
<=3                   10.980769  11.016129             11.000000
>3                     9.628205  10.864000             10.177936
Average sscore total   9.966346  10.914439             10.415190

In [34]:
pd.pivot_table(student,
               index='studytime',
               columns='sex',
               aggfunc={'age':['min', 'max'],
                        'score': 'median'})

                age              score
                max     min     median
sex               F   M   F   M      F     M
studytime
1. <2 hours      18  22  15  15   11.0  10.0
2. 2 - 5 hours   19  20  15  15   10.0  11.0
3. 5 - 10 hours  20  18  15  15   11.0  14.0
4. >10 hours     19  18  15  15   11.0  12.5

In [36]:
pd.pivot_table(student,
               index='studytime',
               values='score',
               columns='sex',
               aggfunc=lambda s:s.max()-s.min())

sex               F   M
studytime
1. <2 hours      18  19
2. 2 - 5 hours   18  19
3. 5 - 10 hours  19   9
4. >10 hours     18  20