In [1]:
import pandas as pd

In [2]:
s = pd.Series([1,2,3,4,5,6,7])

In [3]:
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [4]:
index_day = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
data = [1,2,3,4,5,6,7]

In [5]:
s = pd.Series(data, index=index_day)

In [6]:
s

Monday       1
Tuesday      2
Wednesday    3
Thursday     4
Friday       5
Saturday     6
Sunday       7
dtype: int64

In [8]:
s['Sunday']

np.int64(7)

In [9]:
s.mean()

np.float64(4.0)

In [10]:
s+s

Monday        2
Tuesday       4
Wednesday     6
Thursday      8
Friday       10
Saturday     12
Sunday       14
dtype: int64

In [11]:
s*3

Monday        3
Tuesday       6
Wednesday     9
Thursday     12
Friday       15
Saturday     18
Sunday       21
dtype: int64

In [12]:
df = pd.DataFrame({'first':s, 'second':s*2})
df

           first  second
Monday         1       2
Tuesday        2       4
Wednesday      3       6
Thursday       4       8
Friday         5      10
Saturday       6      12
Sunday         7      14

In [13]:
column_names = ['city','population']
index_country=['Japan','India','China','Brazil','Mexico']

In [14]:
row1=['Tokyo', 37.3]
row2=['Delhi', 45.6]
row3=['Shanghai', 25.3]
row4=['Sao Paulo', 62.3]
row5=['Mexico', 21.3]

data = [row1, row2, row3, row4, row5]
data

[['Tokyo', 37.3],
 ['Delhi', 45.6],
 ['Shanghai', 25.3],
 ['Sao Paulo', 62.3],
 ['Mexico', 21.3]]

In [15]:
df=pd.DataFrame(data, index=index_country, columns=column_names)
df

             city  population
Japan       Tokyo        37.3
India       Delhi        45.6
China    Shanghai        25.3
Brazil  Sao Paulo        62.3
Mexico     Mexico        21.3

In [16]:
cities=['Tokyo','Delhi','Shanghai','Sao Paulo','Mexico']
population=[1,2,3,4,5]

In [17]:
dict_popu = {'City':cities, 'population':population}
dict_popu

{'City': ['Tokyo', 'Delhi', 'Shanghai', 'Sao Paulo', 'Mexico'],
 'population': [1, 2, 3, 4, 5]}

In [18]:
df=pd.DataFrame(dict_popu, index=index_country)

In [19]:
df

             City  population
Japan       Tokyo           1
India       Delhi           2
China    Shanghai           3
Brazil  Sao Paulo           4
Mexico     Mexico           5

In [21]:
df['City']

Japan         Tokyo
India         Delhi
China      Shanghai
Brazil    Sao Paulo
Mexico       Mexico
Name: City, dtype: object