In [12]:
import pandas as pd
df = [[1,2,3,'ram'],[1,'sham',3,5]]
cols=['col1','col2','col3','col4']
df = pd.DataFrame(df, index=['row1', 'row2'], columns=cols)

In [13]:
df

      col1  col2  col3 col4
row1     1     2     3  ram
row2     1  sham     3    5

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      object
 2   col3    2 non-null      int64
 3   col4    2 non-null      object
dtypes: int64(2), object(2)
memory usage: 80.0+ bytes

In [17]:
df['col2'] = df['col2'].astype('int32', errors='ignore')

In [18]:
df

      col1  col2  col3 col4
row1     1     2     3  ram
row2     1  sham     3    5

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      object
 2   col3    2 non-null      int64
 3   col4    2 non-null      object
dtypes: int64(2), object(2)
memory usage: 80.0+ bytes

In [23]:
df.to_csv('temp2.csv', index=False)